name: Continuous Integration

on:
  push:
    branches: [ trunk ]

jobs:

  tests:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Nim
      uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: 'stable'
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Update Nimble
      run: nimble install -y nimble

    - name: Debug build
      run: nimble debug -y

    - name: Install nimalyzer
      run: nimble install -y nimalyzer

    - name: Check with Nimalyzer
      run: nimalyzer tools/nimalyzer.cfg

    - name: Upload the log
      uses: actions/upload-artifact@v3
      if: failure()
      with:
         name: nimalyzer.log
         path: nimalyzer.log

    - name: Run tests
      run: nimble test -y

  build_linux:
    needs: tests
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Nim
      uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: 'stable'
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Update Nimble
      run: nimble install -y nimble

    - name: Release build
      run: nimble -y release

  build_freebsd:
    needs: tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Release build
      uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        prepare: |
          sed -i '' -e 's/quarterly/latest/g' /etc/pkg/FreeBSD.conf
          pkg install -y git nimble
        run: |
          export PATH=$PATH:$HOME/.nimble/bin:/usr/local/nim/bin
          nimble -y release
