name: Continuous Integration

on:
  push:
    branches: [ trunk ]

jobs:

  tests:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache Nim and Nimble
      id: cache-nim
      uses: actions/cache@v2
      with:
        path: |
          ~/.nimble
          ~/.choosenim
        key: ${{ runner.os }}-nim

    - name: Setup Nim
      uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: '1.6.6'

    - name: Debug build
      run: nimble debug

    - name: Run tests
      run: testament pattern "tests/**/*.nim"
