name: Continuous Integration

on:
  push:
    branches: [ trunk ]

jobs:

  tests:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache nimble
      id: cache-nimble
      uses: actions/cache@v2
      with:
        path: ~/.nimble
        key: ${{ runner.os }}-nimble

    - name: Setup Nim
      uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: '1.6.2'

    - name: Debug build
      run: nim debug
