name: Continuous Integration

on:
  push:
    branches: [ trunk ]

jobs:

  tests:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Nim
      uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: 'stable'
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Update Nimble
      run: nimble install -y nimble

    - name: Debug build
      run: nimble debug -y

    - name: Install nimalyzer
      run: nimble install -y nimalyzer@"> 0.6"

    - name: Check with Nimalyzer
      run: nimalyzer tools/nimalyzer.cfg

    - name: Upload the log
      uses: actions/upload-artifact@v3
      if: failure()
      with:
         name: nimalyzer.log
         path: nimalyzer.log

    - name: Run tests
      run: nimble tests -y
