name: Continuous Integration

on:
  push:
    branches: [ trunk ]

jobs:

  tests:

    runs-on: ubuntu-latest

    container: ghcr.io/thindil/nim:latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Debug build
      run: nim debug
